### PR TITLE
4-NF- Issue Template

### LINKED ISSUE #4: NF-Create Templates for this project
# NF Templates for the project

## Description

This issue is for creating and reviewing the templates for issues and pull requests for the project.

## Checklist
- [x] @danycmtz 
- [x] Select labels (optional)
- [x] Associate to the project

## Include feature
- [x] Create a Branch
- [x] Implement the feature
- [x] Create a Pull Request 
- [x] Link the Pull request to the issue

### PR DESCRIPTION
**Pull request by danycmtz**
Closes #4

### CODE REVIEW

**Comment by olafhuerta97** [comment]
Are this all changes in this PR or this is still a WIP?

**Comment by danycmtz** [comment]
Maybe there will be more changes, thanks. I'll let you know.

**Comment by olafhuerta97** [comment]
@danycmtz please change this PR to draft

**Comment by danycmtz** [comment]
@olafhuerta97 Please check the template and let me know if you want me to add or delete something.

**Comment by danycmtz** [comment]
@olafhuerta97 check this, please

**Review by olafhuerta97 — COMMENTED** [review]
Thank you!

**Review by olafhuerta97 — APPROVED** [review]

**Comment by danycmtz** [comment]
Thank you!

**Pull request merged**
